<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>SMS API</h1>
        <div>an SMS API for sending SMS</div>

        <?php if (isset($name) && $name==='send-sms') : ?>
          <h2>Please send a post request to <?= htmlspecialchars($name); ?>!</h2>
        <?php elseif (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p><a href="mailto:info@fahdmurtaza.com">Contact me</a> for buying this service.</p>
        <?php endif; ?>
    </body>
</html>
